### PR TITLE
TweakAutoBadOmen

### PR DESCRIPTION
**Pull request by donatomartin**
No one asked but 1.21 needed a way to AFK 1.20 raid farms, so I added autoconsumption of ominous bottles when placed on any hand and no other Omen effect is active.

I just added conditional click handling in MiscTweaks in case this functionality is required in future tweaks.

This is my first PR on a public repo so please be nice :)

### CODE REVIEW

**Comment by Youmiel** [comment]
As a tech player, I don't think you need a way to AFK 1.20 raid farm in MC 1.21. Raid farms could be redesigned, why do we need a mod to monkey patch out-dated designs?

I suppose it makes more sense if this tweak could be expanded to features like "auto potion" or auto consuming food/potion/stew. Its more powerful and useful (and more hacky ofc).

**Comment by donatomartin** [comment]
I get what you're saying, but as far as some internet browsing could get me, there is no proper way of detecting wether a raid is still going in game.

This tweak aims to be used in those situations. It also contemplates trial omen which could be interesting for other kind of farming.

My personal usecase, I'm not even gonna lie here. These last few days I've been using it to patch my technical minecraft skill issue.

**Comment by donatomartin** [comment]
Auto potion could also be interesting, but I feel like it's behaviour is more predictable as potion effects last for a fixed amount of time. Periodic use can handle that.

**Comment by sakura-ryoko** [comment]
Agree'd

**Pull request closed without merging**
