### PR TITLE
fix: auto detect if the player has permission to query nbt fromserver to prevent sending invalid packets

### PR DESCRIPTION
**Pull request by zly2006**
Hello there,

Here the client first sends an nbt query packet, if the server responds then the player has permission, so we allow sending more packets.

This auto detecting requires `TWEAK_SERVER_ENTITY_DATA_SYNCER` to be true (so I set its default value to true), looks a bit weird because the other options are all false by default. Maybe we should either remove this option, or change it to something like `TWEAK_DISABLE_SERVER_DATA_SYNC`?

I also changed your logger level from warn to debug.

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
> I also changed your logger level from warn to debug.

Yes, I was in the middle of debugging, but had to go to bed

**Comment by sakura-ryoko** [comment]
Also, TWEAK_SERVER_ENTITY_DATA_SYNCER was because when I asked masa, he said to put it behind a setting to stop the sending of the packets if not wanted; like enabling / disabling the feature entirely is the goal.

**Comment by zly2006** [comment]
> Also, TWEAK_SERVER_ENTITY_DATA_SYNCER was because when I asked masa, he said to put it behind a setting to stop the sending of the packets if not wanted; like enabling / disabling the feature entirely is the goal.

 Thanks, **should it be changed into TWEAK_DISABLE_SERVER_DATA_SYNC so it could be false by default?**

> Yes, I was in the middle of debugging, but had to go to bed

Sorry for not testing it in vanilla servers. https://github.com/sakura-ryoko/tweakeroo/pull/1#issuecomment-2180816640  . I will fix it together with the issue above.

**Comment by sakura-ryoko** [comment]
You can rename the setting, thats fine

**Pull request merged**
