### PR TITLE
Easy placement v3 fix

### PR DESCRIPTION
**Pull request by zly2006**

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
I tested the Rails, Leaves, etc under Litematica, and the Crafter / Dropper rotations under Tweakeroo, and noticed that this code "fixes" the invalid button placements.

Any more tests that you think this needs?  I believe this is more of a "polishing" type of fix.

**Comment by zly2006** [comment]
> Any more tests that you think this needs? I believe this is more of a "polishing" type of fix.

I have no idea of that... I have deployed this fix to my server (I treat the invalid block states as an important issue) and hope the players can find something not yet fixed.

**Comment by zly2006** [comment]
And currently `PROPERTY_VALIDATORS` is not really used. If there is eventually no usage of it we should clean it up.

**Comment by sakura-ryoko** [comment]
So basically this fix is just removing unused/buggy Whitelisted Properties ?

**Comment by zly2006** [comment]
> So basically this fix is just removing unused/buggy Whitelisted Properties ?

also check `state.canPlaceAt` so floating buttons wont be placed.

**Comment by sakura-ryoko** [comment]
I put out a release for Litematica to fix another bug, and included the existing code here in the release, for now; so you can use it for testing with sakura.15 of it

**Comment by zly2006** [comment]
I think they can be merged now

**Pull request merged**
