### PR TITLE
feat: auto switch elytra when falling

### PR DESCRIPTION
**Pull request by zly2006**
and back to the previous item when landing.

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
I'll merge this, but it needs to check the this.fallDistance before activating the Elytra Swap, because as-is, you can just "hop" around and constantly swap your elytra and chest.

Don't worry, I'll fix it.

**Comment by zly2006** [comment]
> I'll merge this, but it needs to check the this.fallDistance before activating the Elytra Swap, because as-is, you can just "hop" around and constantly swap your elytra and chest.
> 
> Don't worry, I'll fix it.

No. You should **NOT** check this, imagine you are on the ground, if you are wearing elytra you can double click the space bar and then use a firework rocket to take off. However, requiring fallDiatance >= 20 makes it impossible to take off from the ground.

Also, a small issue when I was testing this feature: when you are jumping, the game is also trying to switch elytra (you can hear a sound, but it is switched back soon), this need more tests.

Btw, you don't need to merge my pull requests so quickly. If you want to fix something you can make changes at my branch and then push to my repo, github will display your changes on this pull request page, and then I can discuss the changes. PRs should be merged only if it seems stable enough imo.

**Comment by zly2006** [comment]
**And why `Inspired by GoodTimeWithScar`**? I was in fact inspired by [this mod](https://github.com/plusls/oh-my-minecraft-client). (I am sure I made this myself, I didn't copy any code of them.)

**Comment by sakura-ryoko** [comment]
> **And why `Inspired by GoodTimeWithScar`**? I was in fact inspired by [this mod](https://github.com/plusls/oh-my-minecraft-client). (I am sure I made this myself, I didn't copy any code of them.)

It was a joke, not sure if you got the joke with it.

**Comment by sakura-ryoko** [comment]
> No. You should **NOT** check this, imagine you are on the ground, if you are wearing elytra you can double click the space bar and then use a firework rocket to take off. However, requiring fallDiatance >= 20 makes it impossible to take off from the ground.

I just tested this, and wearing an Elytra using rockets works as expected.  What was actually happening is, it didn't matter if I was wearing a chestplate, Elytra, or nothing, and just "jumped" around not meaning to take off, the game was just constantly swapping back and forth when I would never want them to swap; since it was not taking into consideration any sort of "falling" even if it was just 1 block high jump.

To me, the meaning of this feature, is to easily swap between an Elytra and Chestplate while falling at least 4-5+ blocks; and not by just "hopping around" .

Perhaps I could make the "fall distance" a configuration, where setting the value to "0" would return the same behavior.

**Comment by zly2006** [comment]
> > No. You should **NOT** check this, imagine you are on the ground, if you are wearing elytra you can double click the space bar and then use a firework rocket to take off. However, requiring fallDiatance >= 20 makes it impossible to take off from the ground.
> 
> I just tested this, and wearing an Elytra using rockets works as expected. What was actually happening is, it didn't matter if I was wearing a chestplate, Elytra, or nothing, and just "jumped" around not meaning to take off, the game was just constantly swapping back and forth when I would never want them to swap; since it was not taking into consideration any sort of "falling" even if it was just 1 block high jump.

If you want to use firework rockets, you must be in a fall flying state, so this is necessary for taking off from the ground.

> To me, the meaning of this feature, is to easily swap between an Elytra and Chestplate while falling at least 4-5+ blocks; and not by just "hopping around" .

This is useful for me, some machines have 1-2 block gap, and this feature helps me jump and fly through the gap.

> Perhaps I could make the "fall distance" a configuration, where setting the value to "0" would return the same behavior.

So I suggest making this option default to 0 for the reasons mentioned above.

**Pull request merged**
