### PR TITLE
Fix Tweakeroo's free camera tweak breaking zoom mods

### PR DESCRIPTION
**Pull request by EnnuiL**
This puts a nail in the coffin of https://github.com/Up-Mods/OkZoomer/issues/48, https://github.com/isXander/Zoomify/issues/216, and really, *any* incompatibility issues involving Tweakeroo's free camera tweak and \<insert zoom mod that does things the proper way here\>; how hasn't this been dealt with here before?

Basically, zoom mods work in a straightforward way: they modify the internal FOV in a way or another (and if they don't and are modifying the game options' FOV, they are going to explode one day); Tweakeroo puts a halt on any attempts to do this while freecam is activated by uh, setting a value at head and cancelling the entire method, not even allowing for other mods to touch it;

This fixes the issue (with a little extra help from MixinExtras) by keeping the FOV as static as possible while also allowing for other mods' mixins to take effect; The end result? In a test instance, Ok Zoomer, Logical Zoom, Zoomify and Zume all can now successfully zoom while Free Camera is enabled, all while the base FOV remains static; heck, even three of these four mods can zoom together with no problems! (Logical Zoom unfortunately does it in a way that cannot stack with other changes)

I'd argue that this code could be further simplified considering that `getFovMultiplier` pretty much only takes effect if the camera entity is a client player (which the free camera is not), but you decide whenever to take that risk or not;

This is the only solution to the problem, there is no reasonable way a zoom mod can fix it itself; please consider this PR

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
Does this also effect 1.21, or just 1.21.3 + ?

Also, generally speaking since Tweakeroo has it's own Zoom tweak it normally hasn't taken other Zoom mods into consideration, I believe.

**Comment by EnnuiL** [comment]
> Does this also effect 1.21, or just 1.21.3 + ?
> 
> Also, generally speaking since Tweakeroo has it's own Zoom tweak it normally hasn't taken other Zoom mods into consideration, I believe.

Ok Zoomer's GH issue has been there since 2021; so I believe it has been broken since 2021 (MC 1.17)! But something tells me that really, it's been broken since forever; therefore I believe backporting doesn't really have a floor limit, it just has to account for version differences if those exist

Oh also yes Tweakeroo has its own zoom, I haven't fixed its inability to interact well with other zoom mods since fixing it would require either modifying behavior (allowing FOV dynamicness to affect zoom and only override the base FOV) or overhauling it with a zoom multiplier/divisor system, which maybe needs extra thought before going forward with it? It shouldn't be a problem though, it's just not as straightforward of a fix as this PR

**Comment by sakura-ryoko** [comment]
The Tweakeroo Zoom FOV value (I don't recall how it's applied), but it is quickly adjustable using the Mouse Wheel, and auto-resets when the Zoom Hotkey is released, if configured to do so.

**Comment by sakura-ryoko** [comment]
I've applied this change to the 1.21 and 1.20.6 repo also; but anything below, such as 1.20.1 / 1.20.4 are still technically Masa's area to operate under.  I can provide him bug fixes and whatnot, but that's it  I do have "bugfix" repo's going back to 1.19.4 for Tweakeroo.

**Comment by EnnuiL** [comment]
> I've applied this change to the 1.21 and 1.20.6 repo also; but anything below, such as 1.20.1 / 1.20.4 are still technically Masa's area to operate under. I can provide him bug fixes and whatnot, but that's it.

Ah that's fair enough, thank you for doing this

**Pull request merged**
