### PR TITLE
fix: sakura-ryoko#84

### PR DESCRIPTION
**Pull request by zly2006**

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
should this be targeted at 1.21.4 ?

**Comment by zly2006** [comment]
This bug happens both on 1.21.3 and .4, so I start fixing from .3, I will test it on .4 soon.

**Comment by sakura-ryoko** [comment]
Anyways thanks for looking at this; it's part of why I didn't do much with it; because I know you were very specific about how it should be working.  What I did was just make it "function" with 1.21.3+, just not fully "fixed" .

**Comment by zly2006** [comment]
Also works on 1.21.4, you can cherry pick this commit and make a release

**Comment by sakura-ryoko** [comment]
Mind if I target it to 1.21.4 then do the Cherry Pick later?

**Comment by zly2006** [comment]
Or I can create another PR pointing to 1.21.4?

**Comment by sakura-ryoko** [comment]
> Mind if I target it to 1.21.4 then do the Cherry Pick later?

Yes, just copy it to a new branch.  It would be easier for my cherry pick to function.

**Comment by sakura-ryoko** [comment]
I'm updating the Malilib, and fixing the Gradle / Loom / Loader stuff.

I leave them alone, and pinned to the "release" versions in case bumping them causes incompatibilities.

**Pull request merged**
