### PR TITLE
PR for Issue #32 - Scroll adjust periodic attack interval while holding the keybind

### PR DESCRIPTION
**Pull request by morgantic**
I managed to create a working build for the Feature Request from https://github.com/sakura-ryoko/tweakeroo/issues/32

This is my first PR on GitHub in ages, I probably did everything wrong, sorry about that X)

### CODE REVIEW

**Comment by zly2006** [comment]
Thanks for your PR. it will be nice if you can also add this to period use.

**Comment by morgantic** [comment]
> Thanks for your PR. it will be nice if you can also add this to period use.

Oh, totally. I completely forgot there are other periodic features. I'll add that as well!

Do you think it would also make sense to be able to scroll adjust the period of the periodicHoldUse and periodicHoldAttack? The hold duration would remain only changeable in the config.

**Comment by zly2006** [comment]
> Do you think it would also make sense to be able to scroll adjust the period of the periodicHoldUse and periodicHoldAttack? The hold duration would remain only changeable in the config.

yes I agree.

**Comment by morgantic** [comment]
Added PERIODIC_USE_INTERVAL, PERIODIC_HOLD_ATTACK_INTERVAL and PERIODIC_HOLD_USE_INTERVAL scroll handlers.

**Review by zly2006 — APPROVED** [review]

**Comment by sakura-ryoko** [comment]
Seems ok, so I'll merge it.

**Pull request merged**
